import assert from 'node:assert/strict';
import test from 'node:test';
import { buildAnalytics,createAnalyticsService,runKMeans } from '../src/services/analyticsService.js';
import type { AnalyticsDatabaseData } from '../src/types/analytics.js';
import type { NormalizedProduct,ProductAggregation } from '../src/types/product.js';

const db:AnalyticsDatabaseData={total_orders:4,valid_orders:3,total_revenue:600,total_customers:2,revenue_trend:[{date:'2026-09-20',revenue:600}],revenue_by_business:[{business:'door',revenue:600},{business:'plug',revenue:0},{business:'brandname',revenue:0},{business:'clothing',revenue:0},{business:'powerbank',revenue:0},{business:'projector',revenue:0}],order_statuses:[{status:'pending',count:1},{status:'completed',count:2},{status:'cancelled',count:1}],top_products:[{product_id:'1',name:'Oak Door',business:'Door',quantity_sold:3,revenue:600}],recent_orders:[]};
const product=(id:string,price:number,stock:number,business:NormalizedProduct['business']='door'):NormalizedProduct=>({id,name:`Product ${id}`,business,business_name:'Door',category:'Doors',price,stock,unit:'piece',status:stock===0?'Out of Stock':stock<=5?'Low Stock':'In Stock',image_url:'',updated_at:''});
const aggregation=(products:NormalizedProduct[]):ProductAggregation=>({products,businesses:[{business:'door',business_name:'Door',status:'online',product_count:products.length},{business:'plug',business_name:'Electrical Plug',status:'unavailable',product_count:0}]});

test('analytics calculates revenue, average order value, stock counts and business totals',()=>{const result=buildAnalytics(db,aggregation([product('1',100,0),product('2',300,3),product('3',800,12)]));assert.equal(result.kpis.total_revenue,600);assert.equal(result.kpis.average_order_value,200);assert.deepEqual([result.kpis.in_stock,result.kpis.low_stock,result.kpis.out_of_stock],[1,1,1]);assert.equal(result.products_by_business.find(x=>x.business==='door')?.count,3);assert.equal(result.order_statuses.find(x=>x.status==='pending')?.count,1);assert.equal(result.top_products[0].quantity_sold,3);});
test('average order value safely handles zero valid orders',()=>assert.equal(buildAnalytics({...db,valid_orders:0,total_revenue:0},aggregation([])).kpis.average_order_value,0));
test('k-means returns deterministic standardized clusters for normal data',()=>{const products=[product('1',10,100),product('2',12,90),product('3',500,4),product('4',550,3),product('5',200,40)];assert.deepEqual(runKMeans(products),runKMeans(products));assert.equal(runKMeans(products).clusters.length,3);assert.equal(runKMeans(products).products.length,5);});
test('k-means handles empty, one, two, fewer-than-k and identical datasets',()=>{assert.deepEqual(runKMeans([]),{products:[],clusters:[]});assert.equal(runKMeans([product('1',5,5)]).clusters.length,1);assert.equal(runKMeans([product('1',5,5),product('2',8,8)]).clusters.length,2);const identical=runKMeans([product('1',5,5),product('2',5,5),product('3',5,5)]);assert.equal(identical.products.length,3);assert.ok(identical.clusters.every(c=>Number.isFinite(c.centroid_price)&&Number.isFinite(c.centroid_stock)));});
test('k-means rejects invalid numeric product features',()=>{const invalid=[product('1',10,2),{...product('2',20,3),price:Number.NaN},{...product('3',20,3),stock:Number.POSITIVE_INFINITY}];assert.deepEqual(runKMeans(invalid).products.map(p=>p.id),['1']);});
test('external product failure is isolated from database analytics',async()=>{const service=createAnalyticsService({load:async()=>db},async()=>{throw new Error('offline')});const result=await service.getAnalytics();assert.equal(result.kpis.total_orders,4);assert.equal(result.kpis.total_products,0);assert.ok(result.warnings.some(x=>x.includes('inventory')));});
