import bcrypt from 'bcryptjs'; import {ApiError} from '../errors/apiError.js'; import {managementRepository} from '../repositories/managementRepository.js'; import type {ManagementRepository,ManagedBusiness} from '../repositories/managementRepository.js'; import type {UserRole} from '../types/user.js';
const rec=(v:unknown)=>typeof v==='object'&&v!==null?v as Record<string,unknown>:{};
const id=(v:string)=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)throw new ApiError(400,'INVALID_ID','Invalid record ID.');return n};
function fields(v:unknown,passwordRequired:boolean){const b=rec(v),name=typeof b.name==='string'?b.name.trim():'',email=typeof b.email==='string'?b.email.trim().toLowerCase():'',role=b.role as UserRole,password=typeof b.password==='string'?b.password:'';if(!name||name.length>160)throw new ApiError(400,'INVALID_NAME','Enter a valid name.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw new ApiError(400,'INVALID_EMAIL','Enter a valid email.');if(!['customer','admin'].includes(role))throw new ApiError(400,'INVALID_ROLE','Select a valid role.');if((passwordRequired||password)&& (password.length<8||password.length>72))throw new ApiError(400,'INVALID_PASSWORD','Password must be between 8 and 72 characters.');return{name,email,role,password}}
function businessFields(v:unknown){const b=rec(v),name=typeof b.name==='string'?b.name.trim():'',api_url=typeof b.api_url==='string'?b.api_url.trim():'',status=b.status as ManagedBusiness['status'];if(!name||name.length>120)throw new ApiError(400,'INVALID_NAME','Enter a valid business name.');if(api_url&&!/^https?:\/\/[^\s]+$/i.test(api_url))throw new ApiError(400,'INVALID_API_URL','Enter a valid HTTP or HTTPS API URL.');if(!['active','inactive','unavailable'].includes(status))throw new ApiError(400,'INVALID_STATUS','Select a valid business status.');return{name,api_url:api_url||null,status}}
export function createManagementService(repo:ManagementRepository=managementRepository){return{
 listUsers:()=>repo.listUsers(),async createUser(p:unknown){const v=fields(p,true);if(await repo.emailExists(v.email))throw new ApiError(409,'EMAIL_TAKEN','An account with this email already exists.');return repo.createUser({...v,password_hash:await bcrypt.hash(v.password,10)})},
 async updateUser(actor:number,key:string,p:unknown){const target=id(key),v=fields(p,false);if(actor===target&&v.role!=='admin')throw new ApiError(409,'SELF_ROLE_PROTECTED','You cannot remove your own administrator role.');if(await repo.emailExists(v.email,target))throw new ApiError(409,'EMAIL_TAKEN','An account with this email already exists.');const found=await repo.updateUser(target,{...v,password_hash:v.password?await bcrypt.hash(v.password,10):undefined});if(!found)throw new ApiError(404,'USER_NOT_FOUND','User not found.');return found},
 async deleteUser(actor:number,key:string){const target=id(key);if(actor===target)throw new ApiError(409,'SELF_DELETE_PROTECTED','You cannot delete your own account.');if(!await repo.deleteUser(target))throw new ApiError(404,'USER_NOT_FOUND','User not found.')},
 listBusinesses:()=>repo.listBusinesses(),async updateBusiness(key:string,p:unknown){const found=await repo.updateBusiness(id(key),businessFields(p));if(!found)throw new ApiError(404,'BUSINESS_NOT_FOUND','Business not found.');return found},
}}
export const managementService=createManagementService();
