import { Router } from 'express';
import { getBusinesses, getHealth, getProducts, getStockSummary } from '../controllers/apiController.js';
import { getMe, postLogin, postLogout, postRegister } from '../controllers/authController.js';
import { getOrderByNumber, getOrders, postOrder } from '../controllers/orderController.js';
import { attachUser, requireAuth } from '../middleware/auth.js';
import { createAdminRouter } from './admin.js';

const router = Router();
router.use(attachUser);
router.get('/health', getHealth);
router.get('/products', getProducts);
router.get('/businesses', getBusinesses);
router.get('/stock/summary', getStockSummary);
router.post('/orders', requireAuth, postOrder);
router.get('/orders', requireAuth, getOrders);
router.get('/orders/:orderNo', requireAuth, getOrderByNumber);
router.post('/auth/register', postRegister);
router.post('/auth/login', postLogin);
router.post('/auth/logout', postLogout);
router.get('/auth/me', getMe);
router.use('/admin', createAdminRouter());
export default router;
