import { mkdirSync } from 'node:fs';
import { open, unlink } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import multer from 'multer';

export const claimUploadDirectory = path.resolve(process.cwd(), 'uploads', 'claims');
export const maxClaimEvidenceBytes = 5 * 1024 * 1024;
export const maxClaimEvidenceFiles = 5;

/** Only names generated by this pipeline are ever stored, and only they can be read back. */
export const claimEvidenceFilePattern = /^[a-f0-9-]{36}\.(?:jpg|png|webp)$/;

mkdirSync(claimUploadDirectory, { recursive: true });

const extensions: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
};

const storage = multer.diskStorage({
  destination: claimUploadDirectory,
  // The client-supplied filename is ignored entirely, so it can never influence the path.
  filename(_request, file, callback) {
    callback(null, `${randomUUID()}${extensions[file.mimetype]}`);
  },
});

export const claimEvidenceUpload = multer({
  storage,
  limits: { fileSize: maxClaimEvidenceBytes, files: maxClaimEvidenceFiles },
  fileFilter(_request, file, callback) {
    if (!extensions[file.mimetype]) {
      callback(new multer.MulterError('LIMIT_UNEXPECTED_FILE', 'evidence'));
      return;
    }
    callback(null, true);
  },
});

/** The declared MIME type is client-controlled, so confirm the file's magic bytes match it. */
export async function hasImageSignature(filePath: string, mimetype: string): Promise<boolean> {
  const handle = await open(filePath, 'r');
  try {
    const buffer = Buffer.alloc(12);
    const { bytesRead } = await handle.read(buffer, 0, 12, 0);
    if (bytesRead < 12) return false;
    if (mimetype === 'image/jpeg') return buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff;
    if (mimetype === 'image/png') return buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    if (mimetype === 'image/webp') return buffer.toString('ascii', 0, 4) === 'RIFF' && buffer.toString('ascii', 8, 12) === 'WEBP';
    return false;
  } finally {
    await handle.close();
  }
}

export async function discardUploadedFiles(files: Array<{ path: string }>): Promise<void> {
  await Promise.all(files.map(file => unlink(file.path).catch(() => undefined)));
}

/**
 * Resolves a stored evidence file to an absolute path. Anything that is not a name this
 * pipeline generated is rejected, which rules out traversal sequences and absolute paths.
 */
export function resolveEvidencePath(fileName: string): string | null {
  if (!claimEvidenceFilePattern.test(fileName)) return null;
  const resolved = path.join(claimUploadDirectory, fileName);
  return path.dirname(resolved) === claimUploadDirectory ? resolved : null;
}
