import { mkdirSync } from 'node:fs';
import { open, unlink } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import multer from 'multer';

export const profileUploadDirectory = path.resolve(process.cwd(), 'uploads', 'profiles');
export const maxProfileImageBytes = 5 * 1024 * 1024;

/** Only URLs generated by this upload pipeline are ever stored, and only they can be deleted. */
export const profileImageUrlPattern = /^\/uploads\/profiles\/[a-f0-9-]{36}\.(?:jpg|png|webp)$/;

mkdirSync(profileUploadDirectory, { recursive: true });

const extensions: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
};

const storage = multer.diskStorage({
  destination: profileUploadDirectory,
  // The client-supplied filename is ignored entirely; the stored name is random.
  filename(_request, file, callback) {
    callback(null, `${randomUUID()}${extensions[file.mimetype]}`);
  },
});

export const profileImageUpload = multer({
  storage,
  limits: { fileSize: maxProfileImageBytes, files: 1 },
  fileFilter(_request, file, callback) {
    if (!extensions[file.mimetype]) {
      callback(new multer.MulterError('LIMIT_UNEXPECTED_FILE', 'image'));
      return;
    }
    callback(null, true);
  },
});

/** The declared MIME type is client-controlled, so confirm the file's magic bytes match it. */
export async function hasImageSignature(filePath: string, mimetype: string): Promise<boolean> {
  const handle = await open(filePath, 'r');
  try {
    const buffer = Buffer.alloc(12);
    const { bytesRead } = await handle.read(buffer, 0, 12, 0);
    if (bytesRead < 12) return false;
    if (mimetype === 'image/jpeg') return buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff;
    if (mimetype === 'image/png') return buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    if (mimetype === 'image/webp') return buffer.toString('ascii', 0, 4) === 'RIFF' && buffer.toString('ascii', 8, 12) === 'WEBP';
    return false;
  } finally {
    await handle.close();
  }
}

export async function discardUploadedFile(filePath: string): Promise<void> {
  await unlink(filePath).catch(() => undefined);
}

/** Deletes a previously stored profile image by its public URL. Anything not matching the strict pattern is ignored. */
export async function deleteStoredProfileImage(imageUrl: string | null | undefined): Promise<void> {
  if (!imageUrl || !profileImageUrlPattern.test(imageUrl)) return;
  await unlink(path.join(profileUploadDirectory, path.basename(imageUrl))).catch(() => undefined);
}
